---

#
# Copyright (c) 2014 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Install runit
  apt: name=runit state=present

- name: Start runsvdir service
  service: name=runsvdir state=started
  ignore_errors: true

- name: Create runit service directories
  file: >
    path="/etc/service/{{ item.name }}"
    state=directory
    owner=root
    group=root
    mode=0755
  with_items: runit_services

- name: Create runit services
  template: >
    src=runit-template
    dest=/etc/service/{{ item.name }}/run
    owner=root
    group=root
    mode=0755
  with_items: runit_services

- name: Wait for runit to discover the new services
  wait_for:
    path: "/etc/service/{{ item.name }}/supervise/ok"
  with_items: runit_services

- name: Stop runit services if required
  shell: >
    sv status {{ item.name }}|grep '^down: '>/dev/null
    && echo 'already stopped'
    || sv stop {{ item.name }}
  when: item.state == 'stopped'
  register: runit_status
  changed_when: runit_status.stdout.find('already stopped') == -1
  with_items: runit_services
