#!/bin/sh

set -e

# Must be a valid filename
NAME="keystone"
PIDFILE="/var/run/$NAME.pid"
#This is the command to be run, give the full pathname
DAEMON="/usr/bin/keystone-all"

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    echo -n "Starting daemon: $NAME"
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" --background --make-pidfile
    echo "."
  ;;
  stop)
    echo -n "Stopping daemon: $NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE"
    echo "."
  ;;
  restart)
    echo -n "Restarting daemon: $NAME"
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile "$PIDFILE"
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" --background --make-pidfile
    echo "."
  ;;
  reload)
    echo -n "Reloading daemon: $NAME"
    kill -HUP $(cat "$PIDFILE")
    echo "."
  ;;
  status)
    echo -n "Restarting daemon: $NAME"
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  *)
  echo "Usage: "$1" {start|stop|restart|status}"
  exit 1
esac

exit 0