#!/bin/sh

set -e

# Must be a valid filename
NAME="neutron-dhcp-agent"
PIDFILE="/var/run/$NAME.pid"
#This is the command to be run, give the full pathname
DAEMON="/usr/bin/neutron-dhcp-agent"
USER="neutron"
DIR="/var/lib/neutron"
EXTRA_OPTS="--config-file=/etc/neutron/neutron.conf --config-file=/etc/neutron/dhcp_agent.ini --log-file=/var/log/neutron/dhcp-agent.log"

. /lib/lsb/init-functions

export PATH="${PATH:+$PATH:}/usr/sbin:/sbin"

case "$1" in
  start)
    mkdir -p /var/run/neutron
    chown neutron:root /var/run/neutron
    if status neutron-ovs-cleanup; then
      start wait-for-state WAIT_FOR=neutron-ovs-cleanup WAIT_STATE=running WAITER=neutron-dhcp-agent
    fi
    echo -n "Starting daemon: $NAME"
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" \
      --background --make-pidfile --chuid "$USER" --chdir "$DIR" \
      -- $EXTRA_OPTS
    echo "."
  ;;
  stop)
    echo -n "Stopping daemon: $NAME"
    start-stop-daemon --stop --quiet --oknodo --pidfile "$PIDFILE"
    echo "."
  ;;
  restart)
    echo -n "Restarting daemon: $NAME"
    start-stop-daemon --stop --quiet --oknodo --retry 30 --pidfile "$PIDFILE"
    start-stop-daemon --start --quiet --pidfile "$PIDFILE" --exec "$DAEMON" \
      --background --make-pidfile --chuid "$USER" --chdir "$DIR"
    echo "."
  ;;
  reload)
    echo -n "Reloading daemon: $NAME"
    kill -HUP $(cat "$PIDFILE")
    echo "."
  ;;
  status)
    echo -n "Restarting daemon: $NAME"
    status_of_proc "$DAEMON" "$NAME" && exit 0 || exit $?
  ;;
  *)
  echo "Usage: "$1" {start|stop|restart|status}"
  exit 1
esac

exit 0
