- name: Start up Auto-DNS docker container
  hosts: localhost

  tasks:
    - name: Start Auto-DNS container
      docker: >
        image=rehabstudio/autodns
        name=autodns
        hostname=autodns
        ports=0.0.0.0:53:53/udp
        volumes=/var/run/docker.sock:/var/run/docker.sock
        detach=yes
        tty=yes
        use_tls=custom
        tls_client_cert=../.docker/cert.pem
        tls_client_key=../.docker/key.pem
        tls_ca_cert=../.docker/ca.pem
        tls_verify_hostname=false
        docker_url=https://{{ docker_host_ip }}:2376
