---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Start up Glance docker container
  hosts: localhost

  tasks:
    - name: Start Glance container
      docker: >
        image=base-image
        name=glance
        hostname={{ GLANCE_HOSTNAME }}
        expose={{ GLANCE_PORT }}
        ports=0.0.0.0:{{ GLANCE_PORT }}:{{ GLANCE_PORT }}
        detach=yes
        tty=yes
        use_tls=custom
        tls_client_cert=../.docker/cert.pem
        tls_client_key=../.docker/key.pem
        tls_ca_cert=../.docker/ca.pem
        tls_verify_hostname=false
        docker_url=https://{{ docker_host_ip }}:2376

    - name: Add Keystone host to inventory
      add_host: name=glance
  tags:
    - glance
    - controller


- name: Configure Glance
  hosts: glance
  connection: docker

  pre_tasks:
    - name: Update apt cache
      apt: update_cache=yes cache_valid_time=7200

    - name: install python-mysqldb
      apt: name="python-mysqldb" state=present

    - name: Provide a fake SysV init script for configuring Glance
      copy: >
        src={{ item.src }}
        dest={{ item.dest }}
        owner=root
        group=root
        mode=0755
      with_items:
        - { src: files/glance-api , dest: /etc/init.d/glance-api }
        - { src: files/glance-registry , dest: /etc/init.d/glance-registry }

  roles:
    - role: openstack-glance
      glance_database_url: "mysql://{{ MYSQL_GLANCE_USER }}:{{ MYSQL_GLANCE_PASS }}@{{ DATABASE_HOSTNAME }}/{{ MYSQL_GLANCE_DB }}"
      glance_hostname: "{{ GLANCE_HOSTNAME }}"
      glance_pass: "{{ GLANCE_PASS }}"
      glance_port: "{{ GLANCE_PORT }}"
      keystone_hostname: "{{ KEYSTONE_HOSTNAME }}"
      rabbit_hostname: "{{ AMQP_HOSTNAME }}"
      rabbit_username: openstack-glance
      rabbit_pass: "{{ RABBIT_GLANCE_PASS }}"

    - role: runit
      runit_services:
        - name: glance-api
          command: |
            start-stop-daemon --start --chuid glance \
              --chdir /var/lib/glance --name glance-api \
              --exec /usr/bin/glance-api
          state: stopped
        - name: glance-registry
          command: |
            start-stop-daemon --start --chuid glance \
              --chdir /var/lib/glance --name glance-registry \
              --exec /usr/bin/glance-registry
          state: stopped
  tags:
    - glance
    - controller
