---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Start up Keystone docker container
  hosts: localhost

  tasks:
    - name: Start Keystone container
      docker: >
        image=base-image
        name=keystone
        hostname={{ KEYSTONE_HOSTNAME }}
        expose={{ KEYSTONE_PORT }},{{ KEYSTONE_ADMIN_PORT }}
        ports=0.0.0.0:{{ KEYSTONE_PORT }}:{{ KEYSTONE_PORT }},0.0.0.0:{{ KEYSTONE_ADMIN_PORT }}:{{ KEYSTONE_ADMIN_PORT }}
        detach=yes
        tty=yes
        use_tls=custom
        tls_client_cert=../.docker/cert.pem
        tls_client_key=../.docker/key.pem
        tls_ca_cert=../.docker/ca.pem
        tls_verify_hostname=false
        docker_url=https://{{ docker_host_ip }}:2376

    - name: Add Keystone host to inventory
      add_host: name=keystone

  tags:
    - keystone
    - controller


- name: Configure Keystone
  hosts: keystone
  connection: docker

  pre_tasks:
    - name: update apt cache
      apt: update_cache=yes cache_valid_time=7200

    - name: install python-mysqldb
      apt: name="python-mysqldb" state=present

    - name: provide a fake SysV init script for configuring keystone
      copy: >
        src=files/keystone
        dest=/etc/init.d/keystone
        owner=root
        group=root
        mode=0755

  roles:
    - role: openstack-keystone
      keystone_database_url: "mysql://{{ MYSQL_KEYSTONE_USER }}:{{ MYSQL_KEYSTONE_PASS }}@{{ DATABASE_HOSTNAME }}/{{ MYSQL_KEYSTONE_DB }}"
      keystone_hostname: "{{ KEYSTONE_HOSTNAME }}"
      keystone_port: "{{ KEYSTONE_PORT }}"
      keystone_admin_port: "{{ KEYSTONE_ADMIN_PORT }}"
      keystone_admin_token: "{{ ADMIN_TOKEN }}"
      keystone_tenants:
        - { name: admin, description: "Admin tenant" }
        - { name: service, description: "Service tenant" }
        - { name: demo, description: "Demo tenant"  }
      keystone_users:
        - { name: admin, password: "{{ ADMIN_PASS }}", tenant: admin }
        - { name: demo, password: "{{ DEMO_PASS }}", tenant: demo }
        - { name: glance, password: "{{ GLANCE_PASS }}", tenant: service }
        - { name: neutron, password: "{{ NEUTRON_PASS }}", tenant: service }
        - { name: nova, password: "{{ NOVA_PASS }}", tenant: service }
      keystone_roles:
        - { name: admin, user: admin, tenant: admin }
        - { name: _member_, user: demo, tenant: demo  }
        - { name: admin, user: glance, tenant: service  }
        - { name: admin, user: neutron, tenant: service  }
        - { name: admin, user: nova, tenant: service  }
      keystone_services:
        - { name: keystone, service_type: identity }
        - { name: glance, service_type: image }
        - { name: neutron, service_type: network }
        - { name: nova, service_type: compute }
      keystone_endpoints:
        - service_name: keystone
          public_url: "{{ KEYSTONE_PROTOCOL }}://{{ KEYSTONE_HOSTNAME}}:{{ KEYSTONE_PORT }}/v2.0"
          internal_url: "{{ KEYSTONE_PROTOCOL }}://{{ KEYSTONE_HOSTNAME}}:{{ KEYSTONE_PORT }}/v2.0"
          admin_url: "{{ KEYSTONE_PROTOCOL }}://{{ KEYSTONE_HOSTNAME}}:{{ KEYSTONE_ADMIN_PORT }}/v2.0"
        - service_name: glance
          public_url: "{{ GLANCE_PROTOCOL }}://{{ GLANCE_HOSTNAME}}:{{ GLANCE_PORT }}/"
          internal_url: "{{ GLANCE_PROTOCOL }}://{{ GLANCE_HOSTNAME}}:{{ GLANCE_PORT }}/"
          admin_url: "{{ GLANCE_PROTOCOL }}://{{ GLANCE_HOSTNAME}}:{{ GLANCE_PORT }}/"
        - service_name: neutron
          public_url: "{{ NEUTRON_PROTOCOL }}://{{ NEUTRON_HOSTNAME}}:{{ NEUTRON_PORT }}/"
          internal_url: "{{ NEUTRON_PROTOCOL }}://{{ NEUTRON_HOSTNAME}}:{{ NEUTRON_PORT }}/"
          admin_url: "{{ NEUTRON_PROTOCOL }}://{{ NEUTRON_HOSTNAME}}:{{ NEUTRON_PORT }}/"
        - service_name: nova
          public_url: "{{ NOVA_API_PROTOCOL }}://{{ NOVA_API_HOSTNAME}}:{{ NOVA_API_PORT }}/v2/%(tenant_id)s"
          internal_url: "{{ NOVA_API_PROTOCOL }}://{{ NOVA_API_HOSTNAME}}:{{ NOVA_API_PORT }}/v2/%(tenant_id)s"
          admin_url: "{{ NOVA_API_PROTOCOL }}://{{ NOVA_API_HOSTNAME}}:{{ NOVA_API_PORT }}/v2/%(tenant_id)s"


    - role: runit
      runit_services:
        - name: keystone
          command: |
            start-stop-daemon --start --chuid keystone \
              --chdir /var/lib/keystone --name keystone \
              --exec /usr/bin/keystone-all
          state: stopped

  tags:
    - keystone
    - controller
