---

#
# Copyright (c) 2015 Davide Guerri <davide.guerri@gmail.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

- name: Start up MySQL docker container
  hosts: localhost

  tasks:
    - name: Start MySQL container
      docker:
        image: dguerri/os-base-image
        name: mysql
        hostname: "{{ DATABASE_HOSTNAME }}"
        expose: 3306
        detach: yes
        tty: yes
        volumes: /var/lib/mysql

    - name: Add MySQL host to inventory
      add_host: name=mysql

  tags:
    - mysql
    - controller


- name: Configure MySQL
  hosts: mysql
  connection: docker

  roles:
    - role: mysql
      mysql_root_password: "{{ MYSQL_ROOT }}"
      mysql_bind_address: 0.0.0.0
      mysql_character_set_server: "utf8"
      mysql_collation_server: "utf8_general_ci"
      mysql_innodb_file_per_table: "innodb_file_per_table"
      mysql_databases:
        - name: "{{ MYSQL_KEYSTONE_DB }}"
          collation: "utf8_general_ci"
          encoding: "utf8"
        - name: "{{ MYSQL_GLANCE_DB }}"
          collation: "utf8_general_ci"
          encoding: "utf8"
        - name: "{{ MYSQL_NEUTRON_DB }}"
          collation: "utf8_general_ci"
          encoding: "utf8"
        - name: "{{ MYSQL_NOVA_DB }}"
          collation: "utf8_general_ci"
          encoding: "utf8"
      mysql_users:
        - name: "{{ MYSQL_KEYSTONE_USER }}"
          pass: "{{ MYSQL_KEYSTONE_PASS }}"
          priv: "{{ MYSQL_KEYSTONE_DB }}.*:ALL"
          host: "%"
        - name: "{{ MYSQL_GLANCE_USER }}"
          pass: "{{ MYSQL_GLANCE_PASS }}"
          priv: "{{ MYSQL_GLANCE_DB }}.*:ALL"
          host: "%"
        - name: "{{ MYSQL_NEUTRON_USER }}"
          pass: "{{ MYSQL_NEUTRON_PASS }}"
          priv: "{{ MYSQL_NEUTRON_DB }}.*:ALL"
          host: "%"
        - name: "{{ MYSQL_NOVA_USER }}"
          pass: "{{ MYSQL_NOVA_PASS }}"
          priv: "{{ MYSQL_NOVA_DB }}.*:ALL"
          host: "%"

    - role: runit
      runit_services:
        - name: mysql
          command: |
            start-stop-daemon --start --name mysql \
              --exec /usr/bin/mysqld_safe
          state: stopped
  tags:
    - mysql
    - controller
